dtc: check.c fix compile error
Fix the following compile error found on odroid-xu4:

checks.c: In function ?check_simple_bus_reg?:
checks.c:876:41: error: format ?%lx? expects argument of type
?long unsigned int?, but argument 4 has type
?uint64_t{aka long long unsigned int}? [-Werror=format=]
  snprintf(unit_addr, sizeof(unit_addr), "%lx", reg);
                                         ^
checks.c:876:41: error: format ?%lx? expects argument of type
?long unsigned int?, but argument 4 has type
?uint64_t {aka long long unsigned int}? [-Werror=format=]
cc1: all warnings being treated as errors
Makefile:304: recipe for target 'checks.o' failed
make: *** [checks.o] Error 1

Signed-off-by: Shuah Khan <shuahkh@osg.samsung.com>
[dwg: Correct new format to be correct in general]
Signed-off-by: David Gibson <david@gibson.dropbear.id.au>
[robh: cherry-picked from upstream dtc commit 2a42b14d0d03]
Signed-off-by: Rob Herring <robh@kernel.org>
Signed-off-by: engstk <eng.stk@sapo.pt>